version: 2

workflows:
  version: 2
  test:
    jobs:
      - test36
      - test37

jobs:
  test36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install --user tox
      - run: tox -e py36

  test37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install --user tox
      - run: tox -e py37
