version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py install
            pip install -r devel-requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py test
